version: '3'

services:

  node:
    build:
      context: ./.docker
      dockerfile: node.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/blockchain
    working_dir: /var/www/blockchain
    networks:
      - nodeapp-network

  testrpc:
    build:
      context: ./.docker
      dockerfile: testrpc.dockerfile
    ports:
      - "8545:8545"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge